name: "Sign"
on:
  push:
    tags:
      - 'v*'
jobs:
  sign:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: "Build"
        run: |
          npm install -g coffee-script
          ./make.js build

      - name: "Sign"
        id: web-ext-sign
        uses: Szczyp/web-ext-sign@v1
        with:
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}
          ignoreFiles: "tests test_harnesses make.js"

      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.web-ext-sign.outputs.target }}
