name: "Test"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Setup Node"
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: "Test"
        run: |
          npm install -g coffee-script
          git submodule update --init --recursive
          npm install puppeteer util
          ./make.js test
